Fix compile error when `FakeParams.new` is called without arguments
```
In src/spec/avram/fake_params.cr:14:8

 14 | .transform_values do |value|
       ^---------------
Error: can't infer block return type, try to cast the block body with `as`. See: https://crystal-lang.org/reference/syntax_and_semantics/as.html#usage-for-when-the-compiler-cant-infer-the-type-of-a-block
```