Fix compile error when `FakeNestedParams.new` is called without arguments
```
In src/spec/avram/fake_nested_params.cr:13:8

 13 | .transform_values &.to_h.transform_keys(&.to_s)
       ^---------------
Error: can't infer block return type, try to cast the block body with `as`. See: https://crystal-lang.org/reference/syntax_and_semantics/as.html#usage-for-when-the-compiler-cant-infer-the-type-of-a-block
```